import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Viewport} from "next";

const inter = Inter({ subsets: ["latin"] });
export const viewport: Viewport = {
  themeColor: 'black',
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
  viewportFit: "cover"
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
